# Generated by Django 4.2.4 on 2023-09-08 06:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
